# Generated by Django 6.0.3 on 2026-03-30 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH')])),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'IN PROGRESS'), (3, 'COMPLETED')])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user'], name='app_categor_user_id_5d0af0_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category'),
        ),
        migrations.AddIndex(
            model_name='tasktable',
            index=models.Index(fields=['user'], name='app_tasktab_user_id_31fee7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktable',
            index=models.Index(fields=['status'], name='app_tasktab_status_66e0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktable',
            index=models.Index(fields=['due_date'], name='app_tasktab_due_dat_a87512_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktable',
            index=models.Index(fields=['is_deleted'], name='app_tasktab_is_dele_11d769_idx'),
        ),
    ]
